
  CREATE TABLE "DWH"."DECLARACIONES" 
   (	"CODIGO" NUMBER(15,0), 
	"ANIO" NUMBER(4,0), 
	"MES" NUMBER(2,0), 
	"CODIGO_SECTOR_N1" VARCHAR2(10 BYTE), 
	"PROVINCIA" VARCHAR2(100 BYTE), 
	"CANTON" VARCHAR2(100 BYTE), 
	"VENTAS_NETAS_12" NUMBER(10,2), 
	"VENTAS_NETAS_0" NUMBER(10,2), 
	"EXPORTACIONES" NUMBER(10,2), 
	"COMPRAS_NETAS_12" NUMBER(10,2), 
	"COMPRAS_NETAS_0" NUMBER(10,2), 
	"IMPORTACIONES" NUMBER(10,2), 
	"COMPRAS_RISE" NUMBER(10,2), 
	"TOTAL_COMPRAS" NUMBER(10,2), 
	"TOTAL_VENTAS" NUMBER(10,2), 
	 PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DWH"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DWH" ;

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "DWH"."DECLARACIONES_TRIGGER1" 
  BEFORE INSERT ON "DECLARACIONES"
  FOR EACH ROW
BEGIN
  SELECT declaraciones_sequence1.nextval
  INTO :new.CODIGO
  FROM dual;
END;
/
ALTER TRIGGER "DWH"."DECLARACIONES_TRIGGER1" ENABLE;

