CREATE TABLE DECLARACIONES.GEOGRAFICA
(
  PROVINCIA   VARCHAR2(100 BYTE),
  CANTON      VARCHAR2(150 BYTE),
  HABITANTES  NUMBER
);

SET DEFINE OFF;
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('AZUAY', 'CUENCA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('AZUAY', 'GIRON');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('AZUAY', 'GUALACEO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('AZUAY', 'NABON');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('AZUAY', 'PAUTE');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('AZUAY', 'PUCARA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('AZUAY', 'SAN FERNANDO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('AZUAY', 'SANTA ISABEL');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('AZUAY', 'SIGSIG');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('AZUAY', 'OÃ`A');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('AZUAY', 'CHORDELEG');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('AZUAY', 'EL PAN');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('AZUAY', 'SEVILLA DE ORO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('AZUAY', 'GUACHAPALA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('AZUAY', 'CAMILO PONCE ENRIQUEZ');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('BOLIVAR', 'GUARANDA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('BOLIVAR', 'CHILLANES');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('BOLIVAR', 'CHIMBO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('BOLIVAR', 'ECHEANDIA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('BOLIVAR', 'SAN MIGUEL');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('BOLIVAR', 'CALUMA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('BOLIVAR', 'LAS NAVES');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('CAÃ`AR', 'AZOGUES');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('CAÃ`AR', 'BIBLIAN');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('CAÃ`AR', 'CAÃ`AR');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('CAÃ`AR', 'LA TRONCAL');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('CAÃ`AR', 'EL TAMBO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('CAÃ`AR', 'DELEG');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('CAÃ`AR', 'SUSCAL');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('CARCHI', 'TULCAN');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('CARCHI', 'BOLIVAR');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('CARCHI', 'ESPEJO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('CARCHI', 'MIRA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('CARCHI', 'MONTUFAR');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('CARCHI', 'SAN PEDRO DE HUACA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('COTOPAXI', 'LATACUNGA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('COTOPAXI', 'LA MANA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('COTOPAXI', 'PANGUA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('COTOPAXI', 'PUJILI');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('COTOPAXI', 'SALCEDO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('COTOPAXI', 'SAQUISILI');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('COTOPAXI', 'SIGCHOS');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('CHIMBORAZO', 'RIOBAMBA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('CHIMBORAZO', 'ALAUSI');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('CHIMBORAZO', 'COLTA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('CHIMBORAZO', 'CHAMBO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('CHIMBORAZO', 'CHUNCHI');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('CHIMBORAZO', 'GUAMOTE');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('CHIMBORAZO', 'GUANO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('CHIMBORAZO', 'PALLATANGA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('CHIMBORAZO', 'PENIPE');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('CHIMBORAZO', 'CUMANDA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('EL ORO', 'MACHALA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('EL ORO', 'ARENILLAS');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('EL ORO', 'ATAHUALPA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('EL ORO', 'BALSAS');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('EL ORO', 'CHILLA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('EL ORO', 'EL GUABO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('EL ORO', 'HUAQUILLAS');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('EL ORO', 'MARCABELI');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('EL ORO', 'PASAJE');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('EL ORO', 'PIÃ`AS');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('EL ORO', 'PORTOVELO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('EL ORO', 'SANTA ROSA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('EL ORO', 'ZARUMA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('EL ORO', 'LAS LAJAS');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('ESMERALDAS', 'ESMERALDAS');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('ESMERALDAS', 'ELOY ALFARO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('ESMERALDAS', 'MUISNE');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('ESMERALDAS', 'QUININDE');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('ESMERALDAS', 'SAN LORENZO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('ESMERALDAS', 'ATACAMES');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('ESMERALDAS', 'RIO VERDE');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GUAYAS', 'GUAYAQUIL');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GUAYAS', 'ALFREDO BAQUERIZO MORENO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GUAYAS', 'BALAO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GUAYAS', 'BALZAR');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GUAYAS', 'COLIMES');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GUAYAS', 'DAULE');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GUAYAS', 'DURAN');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GUAYAS', 'EL EMPALME');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GUAYAS', 'EL TRIUNFO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GUAYAS', 'MILAGRO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GUAYAS', 'NARANJAL');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GUAYAS', 'NARANJITO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GUAYAS', 'PALESTINA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GUAYAS', 'PEDRO CARBO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GUAYAS', 'SAMBORONDON');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GUAYAS', 'SANTA LUCIA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GUAYAS', 'SALITRE');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GUAYAS', 'SAN JACINTO DE YAGUACHI');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GUAYAS', 'PLAYAS');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GUAYAS', 'SIMON BOLIVAR');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GUAYAS', 'CORONEL MARCELINO MARIDUEÃ`A');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GUAYAS', 'LOMAS DE SARGENTILLO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GUAYAS', 'NOBOL');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GUAYAS', 'GENERAL ANTONIO ELIZALDE');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GUAYAS', 'ISIDRO AYORA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('IMBABURA', 'IBARRA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('IMBABURA', 'ANTONIO ANTE');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('IMBABURA', 'COTACACHI');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('IMBABURA', 'OTAVALO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('IMBABURA', 'PIMAMPIRO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('IMBABURA', 'SAN MIGUEL DE URCUQUI');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOJA', 'LOJA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOJA', 'CALVAS');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOJA', 'CATAMAYO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOJA', 'CELICA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOJA', 'CHAHUARPAMBA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOJA', 'ESPINDOLA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOJA', 'GONZANAMA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOJA', 'MACARA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOJA', 'PALTAS');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOJA', 'PUYANGO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOJA', 'SARAGURO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOJA', 'SOZORANGA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOJA', 'ZAPOTILLO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOJA', 'PINDAL');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOJA', 'QUILANGA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOJA', 'OLMEDO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOS RIOS', 'BABAHOYO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOS RIOS', 'BABA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOS RIOS', 'MONTALVO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOS RIOS', 'PUEBLO VIEJO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOS RIOS', 'QUEVEDO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOS RIOS', 'URDANETA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOS RIOS', 'VENTANAS');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOS RIOS', 'VINCES');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOS RIOS', 'PALENQUE');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOS RIOS', 'BUENA FE');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOS RIOS', 'VALENCIA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOS RIOS', 'MOCACHE');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('LOS RIOS', 'QUINSALOMA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MANABI', 'PORTOVIEJO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MANABI', 'BOLIVAR');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MANABI', 'CHONE');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MANABI', 'EL CARMEN');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MANABI', 'FLAVIO ALFARO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MANABI', 'JIPIJAPA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MANABI', 'JUNIN');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MANABI', 'MANTA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MANABI', 'MONTECRISTI');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MANABI', 'PAJAN');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MANABI', 'PICHINCHA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MANABI', 'ROCAFUERTE');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MANABI', 'SANTA ANA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MANABI', 'SUCRE');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MANABI', 'TOSAGUA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MANABI', '24 DE MAYO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MANABI', 'PEDERNALES');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MANABI', 'OLMEDO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MANABI', 'PUERTO LOPEZ');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MANABI', 'JAMA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MANABI', 'JARAMIJO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MANABI', 'SAN VICENTE');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MORONA SANTIAGO', 'MORONA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MORONA SANTIAGO', 'GUALAQUIZA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MORONA SANTIAGO', 'LIMON - INDANZA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MORONA SANTIAGO', 'PALORA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MORONA SANTIAGO', 'SANTIAGO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MORONA SANTIAGO', 'SUCUA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MORONA SANTIAGO', 'HUAMBOYA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MORONA SANTIAGO', 'SAN JUAN BOSCO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MORONA SANTIAGO', 'TAISHA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MORONA SANTIAGO', 'LOGROÃ`O');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MORONA SANTIAGO', 'PABLO SEXTO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('MORONA SANTIAGO', 'TIWINTZA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('NAPO', 'TENA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('NAPO', 'ARCHIDONA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('NAPO', 'EL CHACO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('NAPO', 'QUIJOS');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('NAPO', 'CARLOS JULIO AROSEMENA TOLA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('PASTAZA', 'PASTAZA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('PASTAZA', 'MERA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('PASTAZA', 'SANTA CLARA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('PASTAZA', 'ARAJUNO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('PICHINCHA', 'QUITO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('PICHINCHA', 'CAYAMBE');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('PICHINCHA', 'MEJIA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('PICHINCHA', 'PEDRO MONCAYO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('PICHINCHA', 'RUMIÃ`AHUI');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('PICHINCHA', 'SAN MIGUEL DE LOS BANCOS');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('PICHINCHA', 'PEDRO VICENTE MALDONADO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('PICHINCHA', 'PUERTO QUITO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('TUNGURAHUA', 'AMBATO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('TUNGURAHUA', 'BAÃ`OS DE AGUA SANTA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('TUNGURAHUA', 'CEVALLOS');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('TUNGURAHUA', 'MOCHA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('TUNGURAHUA', 'PATATE');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('TUNGURAHUA', 'QUERO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('TUNGURAHUA', 'SAN PEDRO DE PELILEO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('TUNGURAHUA', 'SANTIAGO DE PILLARO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('TUNGURAHUA', 'TISALEO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('ZAMORA CHINCHIPE', 'ZAMORA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('ZAMORA CHINCHIPE', 'CHINCHIPE');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('ZAMORA CHINCHIPE', 'NANGARITZA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('ZAMORA CHINCHIPE', 'YACUAMBI');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('ZAMORA CHINCHIPE', 'YANTZAZA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('ZAMORA CHINCHIPE', 'EL PANGUI');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('ZAMORA CHINCHIPE', 'CENTINELA DEL CONDOR');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('ZAMORA CHINCHIPE', 'PALANDA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('ZAMORA CHINCHIPE', 'PAQUISHA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GALAPAGOS', 'SAN CRISTOBAL');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GALAPAGOS', 'ISABELA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('GALAPAGOS', 'SANTA CRUZ');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('SUCUMBIOS', 'LAGO AGRIO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('SUCUMBIOS', 'GONZALO PIZARRO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('SUCUMBIOS', 'PUTUMAYO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('SUCUMBIOS', 'SHUSHUFINDI');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('SUCUMBIOS', 'SUCUMBIOS');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('SUCUMBIOS', 'CASCALES');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('SUCUMBIOS', 'CUYABENO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('ORELLANA', 'ORELLANA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('ORELLANA', 'AGUARICO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('ORELLANA', 'LA JOYA DE LOS SACHAS');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('ORELLANA', 'LORETO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('SANTO DOMINGO DE LOS TSACHILAS', 'SANTO DOMINGO');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('SANTO DOMINGO DE LOS TSACHILAS', 'LA CONCORDIA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('SANTA ELENA', 'SANTA ELENA');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('SANTA ELENA', 'LA LIBERTAD');
Insert into DECLARACIONES.GEOGRAFICA
   (PROVINCIA, CANTON)
 Values
   ('SANTA ELENA', 'SALINAS');
COMMIT;


