/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Properties;
import java.sql.*;


/**
 *
 * @author bodg010715
 */
public class Generacion_Declaraciones extends javax.swing.JFrame {
 /* Declaración de un vector de 25 hilos 
    correspondientes a las 24 provincias del país 
    y uno adicional para la generación de datos de
    todas las provincias*/
  hilo_provincia hilo[]=new hilo_provincia[25];
  

 /*Variables auxiliares tipo contador que permiten controlar la ejecución de los hilos */   
   public int contador_provincia[]= new int[25];
    int numero_provincia=0;

    
    
    /**
     * Creates new form Generacion_Declaraciones_Detalle
     */
    public Generacion_Declaraciones() {
        initComponents();
        jbuttonGroup.add(jRadioAzuay);
jbuttonGroup.add(jRadioBolivar);
jbuttonGroup.add(jRadioCarchi);
jbuttonGroup.add(jRadioCanar);
jbuttonGroup.add(jRadioChimborazo);
jbuttonGroup.add(jRadioCotopaxi);
jbuttonGroup.add(jRadioOro);
jbuttonGroup.add(jRadioEsmeraldas);
jbuttonGroup.add(jRadioGalapagos);
jbuttonGroup.add(jRadioGuayas);
jbuttonGroup.add(jRadioImbabura);
jbuttonGroup.add(jRadioLoja);
jbuttonGroup.add(jRadioRios);
jbuttonGroup.add(jRadioManabi);
jbuttonGroup.add(jRadioMorona);
jbuttonGroup.add(jRadioNapo);
jbuttonGroup.add(jRadioOrellana);
jbuttonGroup.add(jRadioPastaza);
jbuttonGroup.add(jRadioZamora);
jbuttonGroup.add(jRadioPichincha);
jbuttonGroup.add(jRadioElena);
jbuttonGroup.add(jRadioDomingo);
jbuttonGroup.add(jRadioSucumbios);
jbuttonGroup.add(jRadioTungurahua);
        for (int i=0; i<25 ;i++){
            hilo[i]=new hilo_provincia(i+1);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbuttonGroup = new javax.swing.ButtonGroup();
        jRadioAzuay = new javax.swing.JRadioButton();
        jRadioBolivar = new javax.swing.JRadioButton();
        jRadioCarchi = new javax.swing.JRadioButton();
        jRadioCanar = new javax.swing.JRadioButton();
        jRadioChimborazo = new javax.swing.JRadioButton();
        jRadioCotopaxi = new javax.swing.JRadioButton();
        jRadioOro = new javax.swing.JRadioButton();
        jRadioEsmeraldas = new javax.swing.JRadioButton();
        jRadioGalapagos = new javax.swing.JRadioButton();
        jRadioGuayas = new javax.swing.JRadioButton();
        jRadioImbabura = new javax.swing.JRadioButton();
        jRadioLoja = new javax.swing.JRadioButton();
        jRadioRios = new javax.swing.JRadioButton();
        jRadioManabi = new javax.swing.JRadioButton();
        jRadioMorona = new javax.swing.JRadioButton();
        jRadioNapo = new javax.swing.JRadioButton();
        jRadioOrellana = new javax.swing.JRadioButton();
        jRadioPastaza = new javax.swing.JRadioButton();
        jRadioZamora = new javax.swing.JRadioButton();
        jRadioPichincha = new javax.swing.JRadioButton();
        jRadioElena = new javax.swing.JRadioButton();
        jRadioDomingo = new javax.swing.JRadioButton();
        jRadioSucumbios = new javax.swing.JRadioButton();
        jRadioTungurahua = new javax.swing.JRadioButton();
        jButtonIniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRadioAzuay.setText("Azuay");
        jRadioAzuay.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioAzuayItemStateChanged(evt);
            }
        });
        jRadioAzuay.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioAzuayStateChanged(evt);
            }
        });
        jRadioAzuay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioAzuayActionPerformed(evt);
            }
        });

        jRadioBolivar.setText("Bolivar");
        jRadioBolivar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioBolivarItemStateChanged(evt);
            }
        });

        jRadioCarchi.setText("Carchi");
        jRadioCarchi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioCarchiItemStateChanged(evt);
            }
        });

        jRadioCanar.setText("Cañar");
        jRadioCanar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioCanarItemStateChanged(evt);
            }
        });

        jRadioChimborazo.setText("Chimborazo");
        jRadioChimborazo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioChimborazoItemStateChanged(evt);
            }
        });

        jRadioCotopaxi.setText("Cotopaxi");
        jRadioCotopaxi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioCotopaxiItemStateChanged(evt);
            }
        });

        jRadioOro.setText("El Oro");
        jRadioOro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioOroItemStateChanged(evt);
            }
        });

        jRadioEsmeraldas.setText("Esmeraldas");
        jRadioEsmeraldas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioEsmeraldasItemStateChanged(evt);
            }
        });

        jRadioGalapagos.setText("Galápagos");
        jRadioGalapagos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioGalapagosItemStateChanged(evt);
            }
        });

        jRadioGuayas.setText("Guayas");
        jRadioGuayas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioGuayasItemStateChanged(evt);
            }
        });

        jRadioImbabura.setText("Imbabura");
        jRadioImbabura.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioImbaburaItemStateChanged(evt);
            }
        });

        jRadioLoja.setText("Loja");
        jRadioLoja.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioLojaItemStateChanged(evt);
            }
        });

        jRadioRios.setText("Los Ríos");
        jRadioRios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioRiosItemStateChanged(evt);
            }
        });

        jRadioManabi.setText("Manabí");
        jRadioManabi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioManabiItemStateChanged(evt);
            }
        });

        jRadioMorona.setText("Morona Santiago");
        jRadioMorona.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioMoronaItemStateChanged(evt);
            }
        });

        jRadioNapo.setText("Napo");
        jRadioNapo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioNapoItemStateChanged(evt);
            }
        });

        jRadioOrellana.setText("Orellana");
        jRadioOrellana.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioOrellanaItemStateChanged(evt);
            }
        });

        jRadioPastaza.setText("Pastaza");
        jRadioPastaza.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioPastazaItemStateChanged(evt);
            }
        });

        jRadioZamora.setText("Zamora");
        jRadioZamora.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioZamoraItemStateChanged(evt);
            }
        });

        jRadioPichincha.setText("Pichincha");
        jRadioPichincha.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioPichinchaItemStateChanged(evt);
            }
        });
        jRadioPichincha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioPichinchaActionPerformed(evt);
            }
        });

        jRadioElena.setText("Santa Elena");
        jRadioElena.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioElenaItemStateChanged(evt);
            }
        });

        jRadioDomingo.setText("Santo Domingo");
        jRadioDomingo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioDomingoItemStateChanged(evt);
            }
        });

        jRadioSucumbios.setText("Sucumbios");
        jRadioSucumbios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioSucumbiosItemStateChanged(evt);
            }
        });

        jRadioTungurahua.setText("Tungurahua");
        jRadioTungurahua.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioTungurahuaItemStateChanged(evt);
            }
        });

        jButtonIniciar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonIniciar.setText("BALANCEAR");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("GENERACION DE DATOS DE DECLARACIONES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioCanar)
                                    .addComponent(jRadioCotopaxi))
                                .addGap(49, 49, 49)
                                .addComponent(jRadioImbabura)
                                .addGap(47, 47, 47)
                                .addComponent(jRadioPastaza)
                                .addGap(105, 105, 105)
                                .addComponent(jRadioTungurahua))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(jRadioGuayas))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(423, 423, 423)
                                .addComponent(jRadioDomingo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(jRadioRios))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jRadioBolivar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(jRadioMorona))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(423, 423, 423)
                                .addComponent(jRadioZamora))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(jRadioEsmeraldas))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(jRadioOro))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jRadioAzuay))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(423, 423, 423)
                                .addComponent(jRadioPichincha))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jRadioCarchi))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(423, 423, 423)
                                .addComponent(jRadioElena))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(423, 423, 423)
                                .addComponent(jRadioSucumbios))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(jRadioLoja))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(jRadioNapo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(jRadioGalapagos))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jRadioChimborazo))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(jRadioManabi))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(jRadioOrellana)))))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jRadioCanar)
                        .addGap(56, 56, 56)
                        .addComponent(jRadioCotopaxi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jRadioImbabura))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jRadioPastaza))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jRadioTungurahua))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jRadioGuayas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jRadioDomingo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jRadioRios))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jRadioBolivar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jRadioMorona))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jRadioZamora))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jRadioEsmeraldas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jRadioOro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jRadioAzuay))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jRadioPichincha))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jRadioCarchi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jRadioElena))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jRadioSucumbios))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jRadioLoja))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jRadioNapo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jRadioGalapagos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jRadioChimborazo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jRadioManabi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jRadioOrellana))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButtonIniciar)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        // TODO add your handling code here:
 
   numero_provincia=24;
   hilo[numero_provincia].activa_hilo();
    for( int i=0; i<24; i++){
                hilo[i].thread.suspend();
           } 
  jbuttonGroup.clearSelection();
  
  
  
//       thread.start();
       
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void jRadioPichinchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioPichinchaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioPichinchaActionPerformed

    private void jRadioAzuayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioAzuayActionPerformed
        
    }//GEN-LAST:event_jRadioAzuayActionPerformed

    private void jRadioAzuayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioAzuayStateChanged
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jRadioAzuayStateChanged

    private void jRadioAzuayItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioAzuayItemStateChanged
        /*Activación y desactivación
        del hilo de ejecución relacionado
        a esta provincia en caso de (de)seleccionar
        este componente
        */
         numero_provincia=0;
        if (jRadioAzuay.isSelected()){
            //Activo el hilo de esta provincia
            hilo[numero_provincia].activa_hilo();
            //desactivo el hilo de generación de cualquier provincia
             hilo[24].desactiva_hilo();
        }
        else{ //desactivo el hilo de esta provincia
            hilo[numero_provincia].desactiva_hilo();
            
        }
      
    }//GEN-LAST:event_jRadioAzuayItemStateChanged

    private void jRadioPichinchaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioPichinchaItemStateChanged
        numero_provincia=18;
        if (jRadioPichincha.isSelected()){
           hilo[numero_provincia].activa_hilo();
            hilo[24].desactiva_hilo();
        }
        else{
            hilo[numero_provincia].desactiva_hilo();
            
        }
    
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioPichinchaItemStateChanged

    private void jRadioBolivarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioBolivarItemStateChanged
        // TODO add your handling code here:
        numero_provincia=1;
        if (jRadioBolivar.isSelected()){
           hilo[numero_provincia].activa_hilo();
            hilo[24].desactiva_hilo();
        }
        else{
            hilo[numero_provincia].desactiva_hilo();
            
        }
    }//GEN-LAST:event_jRadioBolivarItemStateChanged

    private void jRadioCarchiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioCarchiItemStateChanged
        // TODO add your handling code here:
       numero_provincia=2;
        if (jRadioCarchi.isSelected()){
           hilo[numero_provincia].activa_hilo();
            hilo[24].desactiva_hilo();
        }
        else{
            hilo[numero_provincia].desactiva_hilo();
            
        }
    }//GEN-LAST:event_jRadioCarchiItemStateChanged

    private void jRadioCanarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioCanarItemStateChanged
        // TODO add your handling code here:
        numero_provincia=3;
        if (jRadioCanar.isSelected()){
           hilo[numero_provincia].activa_hilo();
            hilo[24].desactiva_hilo();
        }
        else{
            hilo[numero_provincia].desactiva_hilo();
            
        }
    }//GEN-LAST:event_jRadioCanarItemStateChanged

    private void jRadioChimborazoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioChimborazoItemStateChanged
        // TODO add your handling code here:
          numero_provincia=4;
        if (jRadioChimborazo.isSelected()){
           hilo[numero_provincia].activa_hilo();
            hilo[24].desactiva_hilo();
        }
        else{
            hilo[numero_provincia].desactiva_hilo();
            
        }
      
    }//GEN-LAST:event_jRadioChimborazoItemStateChanged

    private void jRadioCotopaxiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioCotopaxiItemStateChanged
        // TODO add your handling code here:
                numero_provincia=5;
        if (jRadioCotopaxi.isSelected()){
           hilo[numero_provincia].activa_hilo();
            hilo[24].desactiva_hilo();
        }
        else{
            hilo[numero_provincia].desactiva_hilo();
            
        }
    }//GEN-LAST:event_jRadioCotopaxiItemStateChanged

    private void jRadioOroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioOroItemStateChanged
        // TODO add your handling code here:
                 numero_provincia=6;
        if (jRadioOro.isSelected()){
           hilo[numero_provincia].activa_hilo();
            hilo[24].desactiva_hilo();
        }
        else{
            hilo[numero_provincia].desactiva_hilo();
            
        }
    }//GEN-LAST:event_jRadioOroItemStateChanged

    private void jRadioEsmeraldasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioEsmeraldasItemStateChanged
        // TODO add your handling code here:
           numero_provincia=7;
        if (jRadioEsmeraldas.isSelected()){
           hilo[numero_provincia].activa_hilo();
            hilo[24].desactiva_hilo();
        }
        else{
            hilo[numero_provincia].desactiva_hilo();
            
        }
        
    }//GEN-LAST:event_jRadioEsmeraldasItemStateChanged

    private void jRadioGalapagosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioGalapagosItemStateChanged
        // TODO add your handling code here:
               numero_provincia=8;
        if (jRadioGalapagos.isSelected()){
           hilo[numero_provincia].activa_hilo();
            hilo[24].desactiva_hilo();
        }
        else{
            hilo[numero_provincia].desactiva_hilo();
            
        }
    }//GEN-LAST:event_jRadioGalapagosItemStateChanged

    private void jRadioGuayasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioGuayasItemStateChanged
        // TODO add your handling code here:
          numero_provincia=9;
        if (jRadioGuayas.isSelected()){
           hilo[numero_provincia].activa_hilo();
            hilo[24].desactiva_hilo();
        }
        else{
            hilo[numero_provincia].desactiva_hilo();
            
        }
    }//GEN-LAST:event_jRadioGuayasItemStateChanged

    private void jRadioImbaburaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioImbaburaItemStateChanged
        // TODO add your handling code here:
            numero_provincia=10;
        if (jRadioImbabura.isSelected()){
           hilo[numero_provincia].activa_hilo();
            hilo[24].desactiva_hilo();
        }
        else{
            hilo[numero_provincia].desactiva_hilo();
            
        }
    }//GEN-LAST:event_jRadioImbaburaItemStateChanged

    private void jRadioLojaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioLojaItemStateChanged
        // TODO add your handling code here:
               numero_provincia=11;
        if (jRadioLoja.isSelected()){
           hilo[numero_provincia].activa_hilo();
            hilo[24].desactiva_hilo();
        }
        else{
            hilo[numero_provincia].desactiva_hilo();
            
        }
    }//GEN-LAST:event_jRadioLojaItemStateChanged

    private void jRadioRiosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioRiosItemStateChanged
        // TODO add your handling code here:
            numero_provincia=12;
        if (jRadioRios.isSelected()){
           hilo[numero_provincia].activa_hilo();
            hilo[24].desactiva_hilo();
        }
        else{
            hilo[numero_provincia].desactiva_hilo();
            
        }
    }//GEN-LAST:event_jRadioRiosItemStateChanged

    private void jRadioManabiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioManabiItemStateChanged
        // TODO add your handling code here:
          numero_provincia=13;
        if (jRadioManabi.isSelected()){
           hilo[numero_provincia].activa_hilo();
            hilo[24].desactiva_hilo();
        }
        else{
            hilo[numero_provincia].desactiva_hilo();
            
        }
    }//GEN-LAST:event_jRadioManabiItemStateChanged

    private void jRadioMoronaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioMoronaItemStateChanged
        // TODO add your handling code here:
          numero_provincia=14;
        if (jRadioMorona.isSelected()){
           hilo[numero_provincia].activa_hilo();
            hilo[24].desactiva_hilo();
        }
        else{
            hilo[numero_provincia].desactiva_hilo();
            
        }
    }//GEN-LAST:event_jRadioMoronaItemStateChanged

    private void jRadioNapoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioNapoItemStateChanged
        // TODO add your handling code here:
          numero_provincia=15;
        if (jRadioNapo.isSelected()){
           hilo[numero_provincia].activa_hilo();
            hilo[24].desactiva_hilo();
        }
        else{
            hilo[numero_provincia].desactiva_hilo();
            
        }
    }//GEN-LAST:event_jRadioNapoItemStateChanged

    private void jRadioOrellanaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioOrellanaItemStateChanged
        // TODO add your handling code here:
          numero_provincia=16;
        if (jRadioOrellana.isSelected()){
           hilo[numero_provincia].activa_hilo();
            hilo[24].desactiva_hilo();
        }
        else{
            hilo[numero_provincia].desactiva_hilo();
            
        }
    }//GEN-LAST:event_jRadioOrellanaItemStateChanged

    private void jRadioPastazaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioPastazaItemStateChanged
        // TODO add your handling code here:
          numero_provincia=17;
        if (jRadioPastaza.isSelected()){
           hilo[numero_provincia].activa_hilo();
            hilo[24].desactiva_hilo();
        }
        else{
            hilo[numero_provincia].desactiva_hilo();
            
        }
    }//GEN-LAST:event_jRadioPastazaItemStateChanged

    private void jRadioElenaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioElenaItemStateChanged
        // TODO add your handling code here:
         numero_provincia=19;
        if (jRadioElena.isSelected()){
           hilo[numero_provincia].activa_hilo();
            hilo[24].desactiva_hilo();
        }
        else{
            hilo[numero_provincia].desactiva_hilo();
            
        }
    }//GEN-LAST:event_jRadioElenaItemStateChanged

    private void jRadioDomingoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioDomingoItemStateChanged
        // TODO add your handling code here:
         numero_provincia=20;
        if (jRadioDomingo.isSelected()){
           hilo[numero_provincia].activa_hilo();
            hilo[24].desactiva_hilo();
        }
        else{
            hilo[numero_provincia].desactiva_hilo();
            
        }
    }//GEN-LAST:event_jRadioDomingoItemStateChanged

    private void jRadioSucumbiosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioSucumbiosItemStateChanged
        // TODO add your handling code here:
         numero_provincia=21;
        if (jRadioSucumbios.isSelected()){
           hilo[numero_provincia].activa_hilo();
            hilo[24].desactiva_hilo();
        }
        else{
            hilo[numero_provincia].desactiva_hilo();
            
        }
    }//GEN-LAST:event_jRadioSucumbiosItemStateChanged

    private void jRadioTungurahuaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioTungurahuaItemStateChanged
        // TODO add your handling code here:
          numero_provincia=22;
        if (jRadioTungurahua.isSelected()){
           hilo[numero_provincia].activa_hilo();
            hilo[24].desactiva_hilo();
        }
        else{
            hilo[numero_provincia].desactiva_hilo();
            
        }
    }//GEN-LAST:event_jRadioTungurahuaItemStateChanged

    private void jRadioZamoraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioZamoraItemStateChanged
        // TODO add your handling code here:
         numero_provincia=23;
        if (jRadioZamora.isSelected()){
           hilo[numero_provincia].activa_hilo();
            hilo[24].desactiva_hilo();
        }
        else{
            hilo[numero_provincia].desactiva_hilo();
            
        }
    }//GEN-LAST:event_jRadioZamoraItemStateChanged

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Generacion_Declaraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Generacion_Declaraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Generacion_Declaraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Generacion_Declaraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Generacion_Declaraciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioAzuay;
    private javax.swing.JRadioButton jRadioBolivar;
    private javax.swing.JRadioButton jRadioCanar;
    private javax.swing.JRadioButton jRadioCarchi;
    private javax.swing.JRadioButton jRadioChimborazo;
    private javax.swing.JRadioButton jRadioCotopaxi;
    private javax.swing.JRadioButton jRadioDomingo;
    private javax.swing.JRadioButton jRadioElena;
    private javax.swing.JRadioButton jRadioEsmeraldas;
    private javax.swing.JRadioButton jRadioGalapagos;
    private javax.swing.JRadioButton jRadioGuayas;
    private javax.swing.JRadioButton jRadioImbabura;
    private javax.swing.JRadioButton jRadioLoja;
    private javax.swing.JRadioButton jRadioManabi;
    private javax.swing.JRadioButton jRadioMorona;
    private javax.swing.JRadioButton jRadioNapo;
    private javax.swing.JRadioButton jRadioOrellana;
    private javax.swing.JRadioButton jRadioOro;
    private javax.swing.JRadioButton jRadioPastaza;
    private javax.swing.JRadioButton jRadioPichincha;
    private javax.swing.JRadioButton jRadioRios;
    private javax.swing.JRadioButton jRadioSucumbios;
    private javax.swing.JRadioButton jRadioTungurahua;
    private javax.swing.JRadioButton jRadioZamora;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.ButtonGroup jbuttonGroup;
    // End of variables declaration//GEN-END:variables
}
